### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by amrapalijz** [MaastrichtU-IDS/RdfUpload#1]
I tried using RdfUpload to upload a ntriples file with 680656 triples but got an error:
➜  RdfUpload git:(master) docker run -it --rm -v /data/hgnc:/data/hgnc rdf-upload -if "/data/hgnc/drill_r2rml_output1.ttl" -ep "http://graphdb.dumontierlab.com/sparql"
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.eclipse.rdf4j.repository.sparql.SPARQLConnection.createDataBody(SPARQLConnection.java:917)
	at org.eclipse.rdf4j.repository.sparql.SPARQLConnection.createInsertDataCommand(SPARQLConnection.java:843)
	at org.eclipse.rdf4j.repository.sparql.SPARQLConnection.add(SPARQLConnection.java:670)
	at org.eclipse.rdf4j.repository.sparql.SPARQLConnection.add(SPARQLConnection.java:507)
	at nl.unimaas.ids.RdfUpload.main(RdfUpload.java:40)

**Comment by amalic** [comment]
We are using now a different method to upload sparql files --> No more heap space errors
